### PR TITLE
Add ability to unmanage rndrelease file

### PR DESCRIPTION
**Pull request by propyless**
There may be a case where we do not want to remove
or modify the rndrelease file.

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
@propyless to speak frankly, I am not so happy with changing the type of $create_rndrelease from boolean to string. I would prefer to bring in an additional variable like $manage_rndrelease to trigger the complete file resource:
<pre>
if $manage_rndrelease == true {
  file { 'arc_rndrelease':
    ensure  => $rndrelease_ensure,
    path    => '/etc/rndrelease',
    mode    => '0644',
    content => "${rndrelease_version_real}\n",
  }
}
</pre>

What do you think ?

**Comment by Phil-Friderici** [comment]
another approach which would keep management of file attributes:

<pre>
class arc (
  $replace_rndrelease = true,
) {
  file { 'arc_rndrelease':
    ensure  => $rndrelease_ensure,
    path    => '/etc/rndrelease',
    mode    => '0644',
    replace => $replace_rndrelease,
    content => "${rndrelease_version_real}\n",
  }
</pre>

**Comment by Phil-Friderici** [comment]
and a last more subtly approach:

<pre>
class arc (
  $rndrelease_path = '/etc/rndrelease',
) {
  file { 'arc_rndrelease':
    ensure  => $rndrelease_ensure,
    path    => $rndrelease_path,
    mode    => '0644',
    content => "${rndrelease_version_real}\n",
  }
</pre>

hahahaha, choose your poison

**Comment by propyless** [comment]
Hello, I would also prefer the first option in that case. I was a bit sceptical to my solution since it checks the validity of the bool after it has checked if its a string containing the word "unmanaged" or not, it makes it sane but not OK.

**Comment by Phil-Friderici** [comment]
@propyless Thanks ! Will be announced with the next update mail :)

**Comment by Phil-Friderici** [comment]
released in v1.2.0

**Pull request merged**
